
project_id = "tvrcfdyhtdihjtvaoyvp"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.send-to-make]
verify_jwt = true

[functions.receive-from-make]
verify_jwt = false
